//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealership.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MakeModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MakeModel()
        {
            this.Cars = new HashSet<Car>();
        }
        public MakeModel(int id, Make make, string name)
        {
            this.ModelId = id;
            this.MakeId = make.MakeId;
            this.Make = make;
            this.Name = name;
            this.Cars = new HashSet<Car>();
        }
        [Key]
        public int ModelId { get; set; }
        public Nullable<int> MakeId { get; set; }
        public string Name { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Cars { get; set; }
        public virtual Make Make { get; set; }
    }
}
