// <auto-generated />
namespace CarDealership.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class featuredcarmerge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(featuredcarmerge));
        
        string IMigrationMetadata.Id
        {
            get { return "202010010317038_featured-car-merge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
